---
title: "DataMiningFinalProject"
output: word_document
---

library(factoextra)
library(NbClust)
library(cluster)
library(stats)
library(ggplot2)
library(ggfortify)
library(dplyr)

mydata <- read.csv("C:/Users/Owner/Desktop/data mining project/mydata.csv")

# plotting the ggplot
ggplot(data= mydata, mapping = aes(x= name, y=calories))+geom_point(size= 2)+geom_line(colour="red")
ggplot(data= mydata, mapping = aes(x= rating, y=calories))+geom_point(size = 2)+geom_line(colour="blue")

# Calculating the euclidean distance
dd <- dist(scale(mydata[70:77, -1]), method = "euclidean")
dd
print(dd, digits=1)
# hierarchical clustering (DENDOGRAM)
#agglomerative clustering 
# complete clustering
set.seed(123)
dataclust <- hclust(dist(mydata[-1]))
plot(dataclust)
plot(dataclust,labels = mydata$name)
rect.hclust(dataclust,10)

#wss plot to choose the minimum number of clusters
wssplot(mydata[-1])

#k-mean clustering

mydata= select(mydata,c(2,3,4,5,6,7,8,9,10))
km<- kmeans(mydata,4)
#Evaluating Cluster Analysis

# Cluster Plot 

autoplot(km, mydata,frame=TRUE)

#Cluster centers

km$centers

#Principle component Analysis

myPr<- prcomp(mydata)
myPr <- prcomp(mydata, scale = TRUE)

#plotting of principle component Analysis

plot(mydata$calories, mydata$vitamins)
plot(scale(mydata$calories), scale(mydata$vitamins))
plot((mydata$calories - mean(mydata$calories)) / sd(mydata$calories))
summary(myPr)
plot(myPr, type = "l")
biplot(myPr)
biplot(myPr, scale = 0)
str(myPr)
myPr$x
mydata2 <- cbind(mydata, myPr$x)
library(ggplot2)

ggplot(mydata2, aes(PC1, PC2, col = mydata$calories, fill = mydata$calories)) +
  stat_ellipse(geom = "polygon", col = "black", alpha = 0.5) +
  geom_point(shape = 21, col = "black")



